"""initial immutable monitoring schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "d80028bc3dc1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "ports",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("destination", sa.String(length=254), nullable=False),
        sa.Column("min_severity", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_rules_owner_id"), "alert_rules", ["owner_id"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("authorized", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("baseline_scan_id", sa.Integer(), nullable=True),
        sa.Column(
            "active_fingerprints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_scan_id"], ["scans.id"], name="fk_target_baseline", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["scan_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_targets_next_scan_at"), "targets", ["next_scan_at"], unique=False)
    op.create_index("ix_targets_owner_host", "targets", ["owner_id", "host"], unique=False)
    op.create_index(op.f("ix_targets_owner_id"), "targets", ["owner_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=100), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["alert_rules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("target_host", sa.String(length=253), nullable=False),
        sa.Column(
            "ports",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Double(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scans_target_id"), "scans", ["target_id"], unique=False)
    op.create_index("ix_scans_target_queued", "scans", ["target_id", "queued_at"], unique=False)
    op.create_index(
        "uq_scans_active_target",
        "scans",
        ["target_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('PENDING','RUNNING')"),
        sqlite_where=sa.text("state IN ('PENDING','RUNNING')"),
    )
    op.create_table(
        "change_candidates",
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("last_scan_id", sa.Integer(), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("target_id", "fingerprint"),
    )
    op.create_table(
        "change_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_change_events_created_at"), "change_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_change_events_severity"), "change_events", ["severity"], unique=False)
    op.create_index(
        op.f("ix_change_events_target_id"), "change_events", ["target_id"], unique=False
    )
    op.create_index(op.f("ix_change_events_type"), "change_events", ["type"], unique=False)
    op.create_table(
        "dns_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column(
            "values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dns_records_scan_id"), "dns_records", ["scan_id"], unique=False)
    op.create_table(
        "scan_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_services_scan_id"), "scan_services", ["scan_id"], unique=False)
    op.create_table(
        "tls_certificates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("not_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tls_certificates_fingerprint"), "tls_certificates", ["fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_tls_certificates_not_after"), "tls_certificates", ["not_after"], unique=False
    )
    op.create_index(
        op.f("ix_tls_certificates_scan_id"), "tls_certificates", ["scan_id"], unique=False
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        op.create_foreign_key(
            "fk_target_baseline", "targets", "scans", ["baseline_scan_id"], ["id"]
        )
    op.create_index(
        "uq_targets_active_owner_host",
        "targets",
        ["owner_id", "host"],
        unique=True,
        postgresql_where=sa.text("archived = false"),
        sqlite_where=sa.text("archived = 0"),
    )


def downgrade():
    op.drop_index("uq_targets_active_owner_host", table_name="targets")
    if op.get_bind().dialect.name == "postgresql":
        op.drop_constraint("fk_target_baseline", "targets", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tls_certificates_scan_id"), table_name="tls_certificates")
    op.drop_index(op.f("ix_tls_certificates_not_after"), table_name="tls_certificates")
    op.drop_index(op.f("ix_tls_certificates_fingerprint"), table_name="tls_certificates")
    op.drop_table("tls_certificates")
    op.drop_index(op.f("ix_scan_services_scan_id"), table_name="scan_services")
    op.drop_table("scan_services")
    op.drop_index(op.f("ix_dns_records_scan_id"), table_name="dns_records")
    op.drop_table("dns_records")
    op.drop_index(op.f("ix_change_events_type"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_target_id"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_severity"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_created_at"), table_name="change_events")
    op.drop_table("change_events")
    op.drop_table("change_candidates")
    op.drop_index(
        "uq_scans_active_target",
        table_name="scans",
        postgresql_where=sa.text("state IN ('PENDING','RUNNING')"),
        sqlite_where=sa.text("state IN ('PENDING','RUNNING')"),
    )
    op.drop_index("ix_scans_target_queued", table_name="scans")
    op.drop_index(op.f("ix_scans_target_id"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_targets_owner_id"), table_name="targets")
    op.drop_index("ix_targets_owner_host", table_name="targets")
    op.drop_index(op.f("ix_targets_next_scan_at"), table_name="targets")
    op.drop_table("targets")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_alert_rules_owner_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_table("users")
    op.drop_table("scan_profiles")
    # ### end Alembic commands ###
